# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f467feb0c769506b1e713233fccfce31f1fa1e5fb7b0e6ea0bb0be51bc05bf58df67584e68efc4d69a326473fbb00dcb47e29d09d9c394f26e3ae7f64169367e

test:
  secret_key_base: 979dc196a963c43db9fa0aff89c625209e91eb5d57c3ea35c3cb9b88b3138c94c888f3052949b9dc06717d8f83dc30eed6b0cda29ae4531e000f05d02eb1819b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
