# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a20bec5e2df983b7ed54386da567913f41eb801bd36e6fb5e1ee6290865fb8f5cb71d32380ee5593e33a75d66c9a16a682dceb58b552adca3fca40d26840c46

test:
  secret_key_base: 74f55b12a8f9a169e83cdb808ee852ef49e982c927fb736b0d7c5881b19afd417aa85faca0878647287f828a6384b03184655cebe7b347abad578fd24a993d76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
